### ISSUE TITLE
GBD Paper Reviewer Comment Tracking

### ISSUE THREAD

**Issue by Jashcraf** [Jashcraf/poke#52]
# Major Comments

## Reviewer 1
- [ ] Better organization of the introductory sections
- [ ] Be sure to reference all figures in the text
- [ ] Add a use case for GBD that only it can resolve

## Reviewer 2
- [ ] Accuracy of VVC Simulation needs to be improved
- [ ] Get comparable results to a wave optics simulation

**Comment by Jashcraf** [comment]
# Minor Comments

## Reviewer 1
- [ ] Line 18: It's unclear how the steps described here enable a more open-source model of the observatory
- [ ] The term observatory appears to sometimes refer to both observatory and instrument, but it's not aways clear when.
- [ ] The abstract suggests that the results demonstrate that GBD is suitable for polarization and misalignment analyses, but the manuscript does not include any demonstration of polarization or misalignment analysis with GBD.
- [ ] The wording around lines 56 appear to exclude any coronagraphic applications less than the most extreme application. This is a weird choice.
- [ ] Line 83 "integrated" -> "integrate"?
- [ ] The sentence that starts on line 85 that includes PROPER, POPPY, etc., just states that these packages "were developed", but doesn't described what they are at all.
- [ ] Line 88 "FALCO" is mentioned without explaining what it is.
- [ ] Line 103: Double parentheses
- [ ] Line 113: "An alternative approach to GBD", an alternative to what ?
- [ ] Line 127: It's not clear that the exit pupil is *always* decomposed into a set of Zernike coefficients before being used.
- [ ] The JATIS Author Guidelines does not allow footnotes (perhaps put URL links in the text)?
- [ ] In Section 1.3, its unclear how critical the issue of vignetting is for the general use of this technique. For example, the Gemini secondary mirror is undersized relative to the primary mirror. How would this effect GBD? In the more general case, is any optical system that includes vignetting/field stops inappropriate for GBD?
- [ ] Line 268, It's not clear in this context exactly what a "input and output" surfaces are. This overall paragraph was not very clear and difficult to follow. It's unclear whether this method is used to calculate a single ray transfer matrix for the entire system, or for each interface. I suspect it's for the entire system, but this could be clarified.
- [ ] Line 273 When referencing 16 unknowns it might be beneficial to refer the reading back to equation 10 as a reminder.
- [ ] Line 268 "The same rays can be traced..." This sentence was quite confusing and I don't understand it.
- [ ] Line 292 "Using this matrix, any open-source diffraction model..." I'm not quite sure what this sentence means.
- [ ] Line 296 "mode Gaussian" -> "Gaussian mode"?
- [ ] Line 302 - beamlets -> beamlets'
- [ ] Line 326 - "the line is defined bt Equation 23" What line?!? No line has been previously discussed.
- [ ] Line 330 - What is n(theta_det)?
- [ ] Line 331 - What is r_0?
- [ ] Equation 24: is theta_det the same thing as theta from Eq'n 23?
- [ ] Line 332: "To propagate the ray to the transversal plane", propagate it from where? The start of the optical system? That doesn't seem right, but it's unclear where we're starting....
- [ ] Equation 25 - What is r'_det?
- [ ] Equation 29 - What is Q_1?
- [ ] Equation 30 - The denominator here appears more complicated than in Equation 2, but it's not exactly clear why. Many terms in the exponent
- [ ] Equation 30 - The formatting of the equation make it difficult to tell if the three e^I terms are being multiplied together, or whether the second two are in the exponent of the first.
- [ ] Equation 30 - There are several new terms here: what is r'_trans'^T? What is r'_trans'?
- [ ] Line 379 - "The coronagraphic simulations" - What simulations? No corona graphic simulations have been previously discussed.
- [ ] Equation 31 - The manuscript appears to be inconsistent in the use of exp(x) vs. e^x.
- [ ] Line 404 - "which we can supply" is odd wording for this step.
- [ ] Line 410 - "Shown below" -> Reference the Figure appropriately!
- [ ] Figure 9 Caption - "2.4m hubble aperture" -> "Hubble Space Telescope" aperture, or HST
- [ ] Figure 9 Caption - "masked region" what is this masked region? It is not defined.
- [ ] Line 437 - "the residuals the propagate through"

## Reviewer 2
- [ ] Line 88: FALCO acronym not defined.
- [ ] Lines 127-128 & 142-143: It isn't necessary to decompose the wavefront into Zernikes. You can easily output a wavefront map from Zemax.
- [ ] Line 289: What is meant by "possibilities for development"?
- [ ] Lines 290-292: This is true, but you first need to calculate the matrix, which takes computation time.
- [ ] Line 317: What is meant by "flexible variant to characterize"?
- [ ] Figure 5: It would be helpful to add the k,r,n vectors to this diagram to pair with equations 18,19,20.
- [ ] Line 327: Something is wrong with the wording here. Remove "including"? Also change end to "detector coordinate at which to evaluate the field."
- [ ] Line 329: Change "the line" to "Eq. 23". Change "plane equation" to "Eq. 22".
- [ ] Line 374: You need to introduce the idea that you are modeling a telescope + coronagraph. Perhaps add "coupled with a vortex coronagraph" to the end of the sentence.
- [ ] A figure showing the optical layout with the coronagraph would be useful here.
- [ ] Table 1: M1 ROC should be positive, not negative. I know this is a Zemax thing, but you should follow typical optics conventions. Also, you could just say "radius" instead of "Semi-Aperture" and then you wouldn't need to explain what it means.
- [ ] Line 380: What does the detector pixel size have to do with the vortex mask sampling? These are completely independent things. The sampling is determined by the focal length of the lens preceding the image plane.
- [ ] Figure 6: "radial oscillation in ^THE^ fractional difference PSF"
- [ ] Line 445: Don't assume your readers speak python: "numpy" "broadcasting" "numexpr"
- [ ] Line 477: Can you quantify how much shorter? Otherwise, this is a throwaway sentence. Everything would be better if it were faster and more accurate.
